[project]
name = "discord-ai-dev-relay"
version = "0.1.0"
description = "Discord bot for sharing text messages between multiple channels"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["discord.py"]

[tool.rye.dev-dependencies]
ruff = "*"